export const SKILL_LIST: { [key: string]: string[] } = {
  unique: [
    '진월아검',
    '칠지천지환류',
    '전멸',
    '필멸',
    '지옥문',
    '진혼제',
    '칼바람',
    '용아귀',
    '천상화',
    '별신제',
    '궤멸',
    '단죄',
  ],
  enchant: ['타계무기', '타계분신', '전우치분신', '구미호분신', '이화선인분신', '싸울아비분신'],
  book: [
    '거마보호방패',
    '검은구체핵',
    '44개의생명',
    '해일강격',
    '화염대법',
    '폭주운기',
    '복희여와의가호',
    '분노의화신',
    '칠흑같은암흑',
    '검은용의공포',
    '건곤권',
    '귀신의몸',
    '호제암격',
  ],
  buff: [
    '보무의목걸이',
    '투명구두',
    '승리의증표',
    '천도의목걸이',
    "수정의귀걸이'보",
    "수정의귀걸이'무",
    "수정의귀걸이'진",
    '사랑의초콜릿귀걸이',
    '행운의초콜릿귀걸이',
    '남북의열정',
    '빛나는마사의귀목',
    '마사의귀목',
    '낡은마사의귀목',
    '[상급]마령의노리개류',
    '[중급]마령의노리개류',
    '[하급]마령의노리개류',
  ],
  set: ['강풍의덫', '귀문방주의보호'],
  status: ['엣헴', '여흥을보여주거라'],
  archeology: ["옴마니반메훔'환", "청룡마령참'환"],
};

export const SKILL_INDEX: { [key: string]: string[] } = {
  빛나는마사의귀목: [],
  마사의귀목: [],
  낡은마사의귀목: [],
  '[상급]마령의노리개류': [],
  '[중급]마령의노리개류': [],
  '[하급]마령의노리개류': [],
  "수정의귀걸이'진": [],
  "수정의귀걸이'보": [],
  "수정의귀걸이'무": [],
  보무의목걸이: [],
  투명구두: [],
  천도의목걸이: [],
  사랑의초콜릿귀걸이: [],
  행운의초콜릿귀걸이: [],
  승리의증표: [],
  남북의열정: [],
  진월아검: ['unique1-1'],
  칠지천지환류: ['unique2-1', 'unique2-2'],
  전멸: ['unique3-1'],
  필멸: ['unique4-1'],
  지옥문: ['unique5-1'],
  진혼제: ['unique6-1'],
  칼바람: ['unique7-1'],
  용아귀: ['unique8-1'],
  천상화: ['unique9-1'],
  별신제: ['unique10-1'],
  궤멸: ['unique11-1'],
  단죄: ['unique12-1'],
  타계분신: [
    'enchant1-1',
    'enchant1-2',
    'enchant1-3',
    'enchant1-4',
    'enchant1-5',
    'enchant1-6',
    'enchant1-7',
    'enchant1-8',
    'enchant1-9',
    'enchant1-10',
    'enchant1-11',
    'enchant1-12',
    'enchant1-13',
    'enchant1-14',
    'enchant1-15',
  ],
  타계무기: [
    'enchant2-1',
    'enchant2-2',
    'enchant2-3',
    'enchant2-4',
    'enchant2-5',
    'enchant2-6',
    'enchant2-7',
    'enchant2-8',
    'enchant2-9',
    'enchant2-10',
    'enchant2-11',
    'enchant2-12',
    'enchant2-13',
    'enchant2-14',
    'enchant2-15',
  ],
  전우치분신: ['enchant3-1', 'enchant3-2', 'enchant3-3', 'enchant3-4', 'enchant3-5', 'enchant3-6', 'enchant3-7'],
  구미호분신: ['enchant4-1', 'enchant4-2', 'enchant4-3', 'enchant4-4', 'enchant4-5', 'enchant4-6', 'enchant4-7'],
  이화선인분신: ['enchant5-1', 'enchant5-2'],
  싸울아비분신: ['enchant6-1', 'enchant6-2'],
  거마보호방패: ['book1-1', 'book1-2', 'book1-3'],
  검은구체핵: ['book2-1', 'book2-2', 'book2-3'],
  '44개의생명': ['book3-1', 'book3-2', 'book3-3'],
  해일강격: ['book4-1', 'book4-2', 'book4-3'],
  화염대법: ['book5-1', 'book5-2', 'book5-3'],
  폭주운기: ['book6-1', 'book6-2', 'book6-3'],
  복희여와의가호: ['book7-1', 'book7-2', 'book7-3'],
  분노의화신: ['book8-1', 'book8-2', 'book8-3'],
  칠흑같은암흑: ['book9-1', 'book9-2', 'book9-3'],
  검은용의공포: ['book10-1', 'book10-2', 'book10-3'],
  건곤권: ['book11-1', 'book11-2', 'book11-3'],
  귀신의몸: ['book12-1', 'book12-2', 'book12-3'],
  호제암격: ['book13-1', 'book13-2', 'book13-3'],
  강풍의덫: ['set1-1', 'set1-2', 'set1-3'],
  귀문방주의보호: ['set2-1'],
  엣헴: ['status1-1'],
  여흥을보여주거라: ['status2-1'],
  "옴마니반메훔'환": ['archeology1-1'],
  "청룡마령참'환": ['archeology2-1'],
};
