export const SKILL_IMAGE_SRC = 'https://jpdkgscyrlhfabjpohmv.supabase.co/storage/v1/object/public/asset/image/skills/';

export const SKILL_LIST: { [key: string]: string[] } = {
  unique: [
    '진월아검',
    '칠지천지환류',
    '전멸',
    '필멸',
    '지옥문',
    '진혼제',
    '칼바람',
    '용아귀',
    '천상화',
    '별신제',
    '궤멸',
    '단죄',
  ],
  enchant: ['타계무기', '타계분신', '전우치분신', '구미호분신', '이화선인분신', '싸울아비분신'],
  book: [
    '거마보호방패',
    '검은구체핵',
    '44개의생명',
    '해일강격',
    '화염대법',
    '폭주운기',
    '복희여와의가호',
    '분노의화신',
    '칠흑같은암흑',
    '검은용의공포',
    '건곤권',
    '귀신의몸',
    '호제암격',
  ],
  buff: [
    '보무의목걸이',
    '투명구두',
    '승리의증표',
    '천도의목걸이',
    "수정의귀걸이'보",
    "수정의귀걸이'무",
    "수정의귀걸이'진",
    '사랑의초콜릿귀걸이',
    '행운의초콜릿귀걸이',
    '남북의열정',
    '빛나는마사의귀목',
    '마사의귀목',
    '낡은마사의귀목',
    '[상급]마령의노리개류',
    '[중급]마령의노리개류',
    '[하급]마령의노리개류',
  ],
  set: ['귀문방주의보호', '강풍의덫'],
  status: ['엣헴', '여흥을보여주거라'],
  archeology: ["옴마니반메훔'환", "청룡마령참'환"],
};

export const SKILL_INDEX: { [key: string]: string[] } = {
  빛나는마사의귀목: [],
  마사의귀목: [],
  낡은마사의귀목: [],
  '[상급]마령의노리개류': [],
  '[중급]마령의노리개류': [],
  '[하급]마령의노리개류': [],
  "수정의귀걸이'진": [],
  "수정의귀걸이'보": [],
  "수정의귀걸이'무": [],
  보무의목걸이: [],
  투명구두: [],
  천도의목걸이: [],
  사랑의초콜릿귀걸이: [],
  행운의초콜릿귀걸이: [],
  승리의증표: [],
  남북의열정: [],
  진월아검: ['unique1'],
  칠지천지환류: ['unique2', 'unique3'],
  전멸: ['unique4'],
  필멸: ['unique5'],
  지옥문: ['unique6'],
  진혼제: ['unique7'],
  칼바람: ['unique8'],
  용아귀: ['unique9'],
  천상화: ['unique10'],
  별신제: ['unique11'],
  궤멸: ['unique12'],
  단죄: ['unique13'],
  타계분신: [
    'enchant1',
    'enchant2',
    'enchant3',
    'enchant4',
    'enchant5',
    'enchant6',
    'enchant7',
    'enchant8',
    'enchant9',
    'enchant10',
    'enchant11',
    'enchant12',
    'enchant13',
    'enchant14',
    'enchant15',
  ],
  타계무기: [
    'enchant16',
    'enchant17',
    'enchant18',
    'enchant19',
    'enchant20',
    'enchant21',
    'enchant22',
    'enchant23',
    'enchant24',
    'enchant25',
    'enchant26',
    'enchant27',
    'enchant28',
    'enchant29',
    'enchant30',
  ],
  전우치분신: ['enchant31', 'enchant32', 'enchant33', 'enchant34', 'enchant35', 'enchant36', 'enchant37'],
  구미호분신: ['enchant38', 'enchant39', 'enchant40', 'enchant41', 'enchant42', 'enchant43', 'enchant44'],
  이화선인분신: ['enchant45', 'enchant46'],
  싸울아비분신: ['enchant47', 'enchant48'],
  거마보호방패: ['book1', 'book2', 'book3'],
  검은구체핵: ['book4', 'book5', 'book6'],
  '44개의생명': ['book7', 'book8', 'book9'],
  해일강격: ['book10', 'book11', 'book12'],
  화염대법: ['book13', 'book14', 'book15'],
  폭주운기: ['book16', 'book17', 'book18'],
  복희여와의가호: ['book19', 'book20', 'book21'],
  분노의화신: ['book22', 'book23', 'book24'],
  칠흑같은암흑: ['book25', 'book26', 'book27'],
  검은용의공포: ['book28', 'book29', 'book30'],
  건곤권: ['book31', 'book32', 'book33'],
  귀신의몸: ['book34', 'book35', 'book36'],
  호제암격: ['book37', 'book38', 'book39'],
  귀문방주의보호: ['set1'],
  강풍의덫: ['set2', 'set3', 'set4'],
  엣헴: ['status1'],
  여흥을보여주거라: ['status2'],
  "옴마니반메훔'환": ['archeology1'],
  "청룡마령참'환": ['archeology2'],
};
